const express = require('express')

const router = express.Router()

const attackCtrl = require('../controllers/attack')

router.post('/person' , attackCtrl.addPerson )
router.patch('/person' , attackCtrl.updatePerson)
router.delete('/person/:id' , attackCtrl.deletePerson )
router.post('/attacked' , attackCtrl.addAttacked)
router.get('/attacked' , attackCtrl.getAttacked)
router.patch('/attacked' , attackCtrl.updateAttacked)
router.delete('/attacked/:id' , attackCtrl.deleteAttacked)
router.post('/simnumber' , attackCtrl.addSimNumber)
router.patch('/simnumber' , attackCtrl.updateSimNumber)
router.delete('/simnumber/:id' , attackCtrl.deleteSimNumber)
router.get('/simnumber' , attackCtrl.getSimNumber)
router.post('/attacking' , attackCtrl.addAttacking)
router.get('/attacking' , attackCtrl.getAttacking)
router.patch('/attacking' , attackCtrl.updateAttacking)
router.delete('/attacking/:id' , attackCtrl.deleteAttacking)
router.post('/attackgroup', attackCtrl.addAttackGroup)
router.patch('/attackgroup' , attackCtrl.updateAttackGroup)
router.delete('/attackgroup' , attackCtrl.deleteAttackGroup)
router.post('/number' , attackCtrl.addNumber)
router.get('/number' , attackCtrl.getNumber)
router.delete('/number/:id' , attackCtrl.deleteNumber)
router.post('/location' , attackCtrl.addLocation)
router.get('/location' , attackCtrl.getLocation)
router.delete('/location/:id' , attackCtrl.deleteLocation)
router.post('/ownership', attackCtrl.addOwnerShip)
router.get('/ownership' , attackCtrl.getOwnerShip)
router.delete('/ownership/:id' , attackCtrl.deleteOwnerShip)
router.post('/operatorname' , attackCtrl.addOperatorName)
router.get('/operatorname' , attackCtrl.getOperatorName)
router.delete('/operatorname/:id' , attackCtrl.deleteOperatorName)

module.exports = router